### ISSUE TITLE
Change logic to send apk to AppCenter

### ISSUE THREAD

**Issue by kode-android** [appKODE/build-publish-plugin#15]
Now we use specific parameters to set timeout and requests count, but it's not so well, because apk can be increased time to time and we should update this parameters in code.

To fix this issue we can calculate timeout and requests count depending on apk size, and make parameters optionals to use it if auto calculation won't work.

**Comment by TrueWarg** [comment]
взял на себя

**Comment by rinekri** [comment]
Merged
