### ISSUE TITLE
Limit changelog length to 5000 characters for AppCenter distribution

### ISSUE THREAD

**Issue by DanilKleshchin** [appKODE/build-publish-plugin#53]
When publishing a build to AppCenter with a changelog exceeding 5000 characters, the following error occurs: `The release notes exceeds the limit of 5000 characters.`. The changelog length has to be limited to 5000 characters.

**Comment by rinekri** [comment]
Fixed in 1.3.0-alpha07

**Comment by rinekri** [comment]
1.3.0-alpha07
